### ISSUE TITLE
Add a License to Project

### ISSUE THREAD

**Issue by depjoys-ops** [depjoys-ops/github-projects-depjoys#3]
Hi @sunbleaks. I wonder what type of license I should add to this project

**Comment by sunbleaks** [comment]
we usually use an MIT license. I think that would be perfect for this project!

**Comment by depjoys-ops** [comment]
Thanks  @sunbleaks, you're  the best. I added the LICENSE file.

**Comment by sunbleaks** [comment]
Ok
